[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["yourpkg"]
src_paths = ["src", "tests"]

[tool.black]
line-length = 88

[tool.mypy]
python_version = "3.11"
pretty = true
warn_unused_ignores = true
warn_redundant_casts = true
no_implicit_optional = false
ignore_missing_imports = true
mypy_path = ["src"]
